services:
  # PHP-FPM сервис
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: telegram-hotel-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - telegram-hotel-network
    depends_on:
      - mysql

  # Nginx веб-сервер
  nginx:
    image: nginx:alpine
    container_name: telegram-hotel-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/ssl:/etc/nginx/ssl:ro
    networks:
      - telegram-hotel-network
    depends_on:
      - app

  # MySQL база данных
  mysql:
    image: mysql:8.0
    container_name: telegram-hotel-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: telegram_hotel
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - telegram-hotel-network

  # phpMyAdmin для управления БД
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: telegram-hotel-phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root_password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "8081:80"
    networks:
      - telegram-hotel-network
    depends_on:
      - mysql

  # Node.js для frontend разработки
  node:
    image: node:20-alpine
    container_name: telegram-hotel-node
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - "5173:5173"
    networks:
      - telegram-hotel-network
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"

  # Redis для кеширования и очередей
  redis:
    image: redis:7-alpine
    container_name: telegram-hotel-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - telegram-hotel-network

networks:
  telegram-hotel-network:
    driver: bridge

volumes:
  mysql_data:
    driver: local 